import test, { after, afterEach, before } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';
import { build } from 'esbuild';
import { JSDOM } from 'jsdom';

const dom = new JSDOM('<!doctype html><div id="root"></div>', { url: 'https://studio.cinematicflight.com/prospecting' });
globalThis.window = dom.window; globalThis.document = dom.window.document; globalThis.HTMLElement = dom.window.HTMLElement; globalThis.IS_REACT_ACT_ENVIRONMENT = true;
let scrollCalls = 0; dom.window.scrollTo = () => { scrollCalls++; };
const { createElement, act } = await import('react'); const { createRoot } = await import('react-dom/client');
let Screen, route, parseMoney, formatMoney, root, compiledDir;

const mission = { public_id: 'mission_1', name: 'Tagaytay villas', objective: 'Find properties whose websites flatten the place.', location: 'Tagaytay', target_categories: ['Private villa'], target_qualified_leads: 5, minimum_score: 75, mission_budget_centavos: 10000, status: 'RUNNING', created_at: '2026-09-02 08:00:00', updated_at: '2026-09-02 08:00:00' };
const prospect = { public_id: 'prospect_1', business_name: 'Casa Verde Resort', category: 'Private villa', address: 'Ridge road', location: 'Tagaytay', website: 'https://example.com', phone: '+63 900 000 0000', status: 'PENDING_APPROVAL', contact_status: 'FOUND', created_at: '2026-09-02 08:00:00', updated_at: '2026-09-02 09:00:00' };
const qualification = { public_id: 'qualification_1', version: 2, experience_gap_score: 95, walkthrough_fit_score: 96, commercial_fit_score: 98, visual_property_score: 100, contactability_score: 98, penalty_score: -20, final_score: 77, priority: 'HIGH', qualification_status: 'QUALIFIED', confidence: .83, experience_gap_summary: 'The stored pages present spaces individually instead of as one connected arrival.', primary_marketing_problem: 'Disconnected static property presentation', cinematicflight_opportunity: 'Create a connected journey from arrival through the major spaces.', scoring_rule_version: 'cinematicflight-v1', created_at: '2026-09-02 09:00:00' };
const reservation = { public_id: 'reservation_1', mission_public_id: mission.public_id, prospect_public_id: prospect.public_id, provider: 'fixture-provider', operation: 'inspect_page', estimated_cost_centavos: 125, reserved_cost_centavos: 125, actual_cost_centavos: null, status: 'RESERVED', created_at: '2026-09-02 09:00:00' };
const run = { public_id: 'agent-run_1', mission_id: mission.public_id, prospect_id: prospect.public_id, status: 'STOPPED', stop_reason: 'HUMAN_APPROVAL_REQUIRED', step_count: 2, llm_call_count: 0, research_duration_ms: 1820, created_at: '2026-09-02 09:00:00' };
const decision = { public_id: 'decision_1', step_number: 1, action: 'INSPECT_PAGE', reason: 'Need first-party evidence about the gallery.', target: 'https://example.com/gallery', authority_result: 'ALLOWED', budget_result: 'ALLOW_FREE', estimated_cost_centavos: 0, actual_cost_centavos: 0, confidence: .83, governance_trace: { final: { result: 'ALLOW' } }, created_at: '2026-09-02 09:00:00' };

function clientFixture(options = {}) {
  const state = { missions: options.empty ? [] : [structuredClone(mission)], prospects: options.empty ? [] : [structuredClone(prospect)], approvals: [], createdMission: null, createdProspect: null, linked: null, approvalPending: null };
  const client = {
    listMissions: async () => structuredClone(state.missions), listProspects: async () => structuredClone(state.prospects), listRuns: async () => options.empty ? [] : [structuredClone(run)], listReservations: async () => options.empty ? [] : [structuredClone(reservation)],
    getMissionCosts: async () => ({ mission_budget_centavos: 10000, actual_cost_centavos: 250, estimated_cost_centavos: 300, remaining_budget_centavos: 9750 }), listMissionProspects: async () => options.empty ? [] : [{ prospect_public_id: prospect.public_id, business_name: prospect.business_name, category: prospect.category, location: prospect.location, mission_status: 'ACTIVE' }],
    listQualifications: async () => options.empty ? [] : [structuredClone(qualification)], getProspect: async () => structuredClone(state.prospects[0]), listEvidence: async () => options.empty ? [] : [{ public_id: 'evidence_1', source_type: 'WEBSITE', source_url: 'https://example.com/gallery', page_title: 'Gallery page', observation_type: 'GALLERY', observation: 'Static image gallery detected.', claim: 'No connected walkthrough was observed on this inspected page.', captured_at: '2026-09-02 09:00:00' }], listContacts: async () => options.empty ? [] : [{ public_id: 'contact_1', type: 'EMAIL', value: 'hello@example.com', source_url: 'https://example.com/contact', verification_status: 'VERIFIED', is_primary: true }], listArtifacts: async () => options.empty ? [] : [{ public_id: 'artifact_1', type: 'WALKTHROUGH_CONCEPT', version: 1, content: { scenes: ['Arrival', 'Villa', 'Pool'] } }, { public_id: 'artifact_2', type: 'OUTREACH_DRAFT', version: 1, content: 'A private draft.' }], listApprovals: async () => structuredClone(state.approvals), listDecisions: async () => [structuredClone(decision)], listWebsiteResearchRequests: async () => [],
    createMission: async (payload) => { if (options.createMissionError) throw new Error('Mission could not be saved.'); state.createdMission = payload; const item = { ...mission, ...payload, public_id: 'mission_new' }; state.missions.unshift(item); return item; }, updateMission: async (id, payload) => { Object.assign(state.missions.find((item) => item.public_id === id), payload); return structuredClone(state.missions[0]); },
    createProspect: async (payload) => { state.createdProspect = payload; const item = { ...prospect, ...payload, public_id: 'prospect_new', status: 'DISCOVERED' }; state.prospects.unshift(item); return item; }, addMissionProspect: async (missionId, prospectId) => { state.linked = { missionId, prospectId }; return {}; },
    createApproval: async (...args) => { state.approvalPending = args; if (options.approvalDeferred) return options.approvalDeferred.promise; if (options.approvalError) throw new Error('Approval was not saved.'); state.approvals.push({ public_id: 'approval_1', action: args[1].action, status: 'APPROVED', created_at: '2026-09-02 10:00:00' }); state.prospects[0].status = args[1].action === 'APPROVE_PROSPECT' ? 'APPROVED' : 'REJECTED'; return state.approvals[0]; },
  }; return { client, state };
}

function deferred() { let resolve; const promise = new Promise((done) => { resolve = done; }); return { promise, resolve }; }
const button = (text) => [...document.querySelectorAll('button')].find((item) => item.textContent.toLowerCase().includes(text.toLowerCase()));
const lastButton = (text) => [...document.querySelectorAll('button')].filter((item) => item.textContent.toLowerCase().includes(text.toLowerCase())).at(-1);
async function click(element) { assert.ok(element, 'control exists'); await act(async () => element.click()); }
async function change(labelText, value) { const label = [...document.querySelectorAll('label')].filter((item) => item.textContent.toLowerCase().includes(labelText.toLowerCase())).at(-1); assert.ok(label, `label ${labelText} exists`); const element = label.querySelector('input,textarea,select'); await act(async () => { const prototype = element.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : element.tagName === 'SELECT' ? window.HTMLSelectElement.prototype : window.HTMLInputElement.prototype; Object.getOwnPropertyDescriptor(prototype, 'value').set.call(element, value); element.dispatchEvent(new window.Event('input', { bubbles: true })); element.dispatchEvent(new window.Event('change', { bubbles: true })); }); }
async function flush() { await act(async () => { await new Promise((resolve) => setTimeout(resolve, 0)); }); }
async function mount(path, context = clientFixture()) { window.history.replaceState({}, '', path); root = createRoot(document.getElementById('root')); await act(async () => root.render(createElement(Screen, { routePath: path, client: context.client, onNavigate: () => {}, onSessionExpired: context.onSessionExpired }))); await flush(); return context; }

before(async () => {
  const require = createRequire(import.meta.url); const result = await build({ entryPoints: ['src/prospecting/ProspectingWorkspace.jsx'], bundle: true, write: false, format: 'esm', platform: 'node', jsx: 'automatic', loader: { '.css': 'empty' }, plugins: [{ name: 'shared-react', setup(bundle) { bundle.onResolve({ filter: /^react(?:-dom)?(?:\/.*)?$/ }, (args) => ({ path: require.resolve(args.path), external: true })); } }] }); compiledDir = await mkdtemp(join(tmpdir(), 'cf-prospecting-ui-')); const file = join(compiledDir, 'screen.mjs'); await writeFile(file, result.outputFiles[0].text); const module = await import(pathToFileURL(file).href); Screen = module.default; route = module.prospectingRoute; parseMoney = module.parsePhpToCentavos; formatMoney = module.formatPhpCentavos;
});
afterEach(async () => { if (root) await act(async () => root.unmount()); root = null; document.getElementById('root').replaceChildren(); });
after(async () => { if (compiledDir) await rm(compiledDir, { recursive: true }); dom.window.close(); });

test('Studio prospecting routes resolve without a router framework', () => { assert.deepEqual(route('/prospecting'), { view: 'overview', id: null }); assert.deepEqual(route('/prospecting/missions/mission_1'), { view: 'mission', id: 'mission_1' }); assert.deepEqual(route('/prospecting/prospects/prospect_1'), { view: 'prospect', id: 'prospect_1' }); assert.deepEqual(route('/prospecting/activity'), { view: 'activity', id: null }); });
test('Prospecting route changes return the workspace to the top', async () => { scrollCalls = 0; await mount('/prospecting/missions'); assert.equal(scrollCalls, 1); });
test('public and demo routing do not expose Prospecting', async () => { const main = await readFile('src/main.jsx', 'utf8'); const dashboard = await readFile('src/SalesDashboard.jsx', 'utf8'); assert.match(main, /isStudioBuild \|\| window\.location\.pathname\.startsWith\("\/dashboard"\)/); assert.doesNotMatch(main, /pathname\.startsWith\("\/prospecting"\)/); assert.match(dashboard, /cloudUser \? \[\.\.\.navItems, prospectingNavItem, reviewNavItem\] : navItems/); });
test('API failure hides all private records and offers no demo fallback', async () => { const context = clientFixture(); context.client.listMissions = async () => { throw new Error('Studio unavailable'); }; await mount('/prospecting', context); assert.match(document.body.textContent, /Prospecting data is unavailable/); assert.doesNotMatch(document.body.textContent, /Casa Verde|Tagaytay villas/); assert.match(document.body.textContent, /Retry secure connection/); });
test('authentication failure expires the Studio session and hides data', async () => { let expired = 0; const context = clientFixture(); context.onSessionExpired = () => { expired++; }; context.client.listMissions = async () => { throw Object.assign(new Error('Sign in again.'), { status: 401 }); }; await mount('/prospecting', context); assert.equal(expired, 1); assert.doesNotMatch(document.body.textContent, /Casa Verde/); });
test('overview derives real metrics and states autonomy is disabled', async () => { await mount('/prospecting'); assert.match(document.body.textContent, /Active missions/); assert.match(document.body.textContent, /Autonomous research and outreach are not enabled/); assert.match(document.body.textContent, /Casa Verde Resort/); });
test('mission and prospect empty states describe manual future-safe behavior', async () => { const context = clientFixture({ empty: true }); await mount('/prospecting/missions', context); assert.match(document.body.textContent, /No missions yet/); await act(async () => root.unmount()); root = null; document.getElementById('root').replaceChildren(); await mount('/prospecting/prospects', clientFixture({ empty: true })); assert.match(document.body.textContent, /Automated discovery will be introduced in a later phase/); });
test('mission list renders budgets, spend and valid lifecycle status', async () => { await mount('/prospecting/missions'); assert.match(document.body.textContent, /Tagaytay villas/); assert.match(document.body.textContent, /₱100\.00/); assert.match(document.body.textContent, /₱97\.50/); assert.match(document.body.textContent, /Running/); });
test('mission form validates and converts PHP text to integer centavos', async () => { const context = await mount('/prospecting/missions'); await click(button('Create mission')); await change('Mission name', 'New mission'); await change('Location', 'Batangas'); await change('Objective', 'Review coastal villas.'); await change('Target categories', 'Villa, Resort'); await change('Target qualified leads', '3'); await change('Minimum score', '76'); await change('Mission budget PHP', '1,234.56'); await click(lastButton('Create mission')); await flush(); assert.equal(context.state.createdMission.mission_budget_centavos, 123456); assert.deepEqual(context.state.createdMission.target_categories, ['Villa', 'Resort']); });
test('invalid mission currency is rejected before any API mutation', async () => { const context = await mount('/prospecting/missions'); await click(button('Create mission')); await change('Mission name', 'New mission'); await change('Location', 'Batangas'); await change('Objective', 'Review villas.'); await change('Target categories', 'Villa'); await change('Mission budget PHP', '10.999'); await click(lastButton('Create mission')); assert.equal(context.state.createdMission, null); assert.match(document.body.textContent, /no more than two decimal places/); });
test('mission server errors remain in the form without false success', async () => { await mount('/prospecting/missions', clientFixture({ createMissionError: true })); await click(button('Create mission')); await change('Mission name', 'New mission'); await change('Location', 'Batangas'); await change('Objective', 'Review villas.'); await change('Target categories', 'Villa'); await change('Mission budget PHP', '100'); await click(lastButton('Create mission')); await flush(); assert.match(document.body.textContent, /Mission could not be saved/); assert.ok(document.querySelector('[aria-label="Create mission"]')); });
test('currency helpers use exact string and integer centavo conversions', () => { assert.equal(parseMoney('1,234.56'), 123456); assert.equal(parseMoney('0.1'), 10); assert.equal(parseMoney('1.001'), null); assert.equal(formatMoney(123456), '₱1,234.56'); });
test('manual prospect creation makes no research call and links the chosen mission', async () => { const context = await mount('/prospecting/prospects'); await click(button('Add prospect')); await change('Business name', 'Manual Villa'); await change('Category', 'Villa'); await change('Location', 'Batangas'); await change('Website', 'https://manual.example'); await click(lastButton('Add prospect')); await flush(); assert.equal(context.state.createdProspect.business_name, 'Manual Villa'); assert.equal(context.state.createdProspect.website, 'https://manual.example'); assert.equal(context.state.linked.missionId, mission.public_id); assert.equal(context.state.linked.prospectId, 'prospect_new'); });
test('prospect list renders status, qualification, contact and mission context', async () => { await mount('/prospecting/prospects'); assert.match(document.body.textContent, /Casa Verde Resort/); assert.match(document.body.textContent, /Pending approval/); assert.match(document.body.textContent, /77/); assert.match(document.body.textContent, /High/); assert.match(document.body.textContent, /Tagaytay villas/); });
test('prospect detail explains score, penalty, evidence and experience gap', async () => { await mount('/prospecting/prospects/prospect_1'); assert.match(document.body.textContent, /Experience gap/); assert.match(document.body.textContent, /95/); assert.match(document.body.textContent, /Penalty/); assert.match(document.body.textContent, /-20/); assert.match(document.body.textContent, /Static image gallery detected/); assert.match(document.body.textContent, /No connected walkthrough was observed/); assert.match(document.body.textContent, /Disconnected static property presentation/); });
test('contacts are observed and verified without guessed-contact behavior', async () => { await mount('/prospecting/prospects/prospect_1'); assert.match(document.body.textContent, /hello@example\.com/); assert.match(document.body.textContent, /Verified/); assert.match(document.body.textContent, /Primary observed contact/); assert.doesNotMatch(document.body.textContent, /guessed email/i); });
test('artifacts render a stored journey and outreach remains clearly unsent', async () => { await mount('/prospecting/prospects/prospect_1'); assert.match(document.body.textContent, /Arrival/); assert.match(document.body.textContent, /Villa/); assert.match(document.body.textContent, /Draft — not sent/i); assert.equal(button('Send'), undefined); assert.equal(button('Email now'), undefined); });
test('empty prospect sections do not imply research has run', async () => { const context = clientFixture({ empty: true }); context.state.prospects = [{ ...prospect, status: 'DISCOVERED' }]; await mount('/prospecting/prospects/prospect_1', context); assert.match(document.body.textContent, /No evidence yet/); assert.match(document.body.textContent, /Research has not been run/); assert.match(document.body.textContent, /No qualification yet/); assert.match(document.body.textContent, /No agent activity yet/); });
test('approval confirmation waits for the server response before showing success', async () => { const pending = deferred(); const context = clientFixture({ approvalDeferred: pending }); await mount('/prospecting/prospects/prospect_1', context); await click(button('Approve prospect')); assert.match(document.body.textContent, /Approve Casa Verde Resort/); await click([...document.querySelectorAll('button')].filter((item) => item.textContent.includes('Approve prospect')).at(-1)); assert.match(document.body.textContent, /Waiting for Studio/); assert.match(document.body.textContent, /Pending approval/); await act(async () => pending.resolve({ public_id: 'approval_1' })); await flush(); });
test('approval errors remain visible and never show false success', async () => { const context = clientFixture({ approvalError: true }); await mount('/prospecting/prospects/prospect_1', context); await click(button('Reject prospect')); await click([...document.querySelectorAll('button')].filter((item) => item.textContent.includes('Reject prospect')).at(-1)); await flush(); assert.match(document.body.textContent, /Approval was not saved/); assert.match(document.body.textContent, /Reject Casa Verde Resort/); assert.doesNotMatch(document.body.textContent, /was recorded/); });
test('agent activity renders run, decision and readable governance results', async () => { await mount('/prospecting/activity'); assert.match(document.body.textContent, /Human approval required/); const details = document.querySelector('.run-list > details'); details.open = true; await act(async () => details.dispatchEvent(new window.Event('toggle'))); await flush(); assert.match(document.body.textContent, /Inspect page/); assert.match(document.body.textContent, /Need first-party evidence/); assert.match(document.body.textContent, /Allow — no cost/); assert.match(document.body.textContent, /Governance trace/); });
test('activity empty state says autonomous research is not enabled', async () => { await mount('/prospecting/activity', clientFixture({ empty: true })); assert.match(document.body.textContent, /No agent activity yet/); assert.match(document.body.textContent, /Autonomous research is not enabled yet/); });
test('costs render committed and reserved integer-centavo amounts', async () => { await mount('/prospecting/costs'); assert.match(document.body.textContent, /Committed spend/); assert.match(document.body.textContent, /₱2\.50/); assert.match(document.body.textContent, /₱1\.25/); assert.match(document.body.textContent, /Fixture-provider/i); assert.match(document.body.textContent, /consolidated cost-event list is a future summary endpoint/i); });
