<?php
declare(strict_types=1);

$pdo=new PDO('mysql:host=db;dbname=review_test;charset=utf8mb4','root','fictional-local-test-only',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$migration=file_get_contents('/app/database/mysql-prospecting-execution-v1.sql');$pdo->exec($migration);$pdo->exec($migration);
$checks=0;
function echeck(bool $ok,string $label):void{global $checks;if(!$ok)throw new RuntimeException('FAIL: '.$label);$checks++;echo "PASS: {$label}\n";}
$tables=$pdo->query("select count(*) from information_schema.tables where table_schema='review_test' and table_name in ('prospecting_budget_reservations','prospecting_agent_ingest_requests')")->fetchColumn();echeck((int)$tables===2,'Phase 3.5 migration creates both additive tables idempotently');

$tokenOne=str_repeat('c',64);$tokenTwo=str_repeat('d',64);$configPath=tempnam(sys_get_temp_dir(),'cf-execution-config-');
$config=['db_host'=>'db','db_name'=>'review_test','db_user'=>'root','db_password'=>'fictional-local-test-only','allowed_origin'=>'http://127.0.0.1:8102','setup_token'=>'disabled','prospecting_agent_ingest_enabled'=>true,'prospecting_agent_monthly_budget_centavos'=>2000,'prospecting_agent_tokens'=>[1=>$tokenOne,2=>$tokenTwo],'prospecting_agent_previous_tokens'=>[]];
file_put_contents($configPath,'<?php return '.var_export($config,true).';');$log=tempnam(sys_get_temp_dir(),'cf-execution-log-');
$process=proc_open(['php','-S','127.0.0.1:8102','-t','/app/public'],[0=>['pipe','r'],1=>['file',$log,'a'],2=>['file',$log,'a']],$pipes,'/app',['CINEMATIC_FLIGHT_CONFIG_PATH'=>$configPath]);if(!is_resource($process))throw new RuntimeException('Could not start isolated execution API.');fclose($pipes[0]);
register_shutdown_function(static function()use($process,$configPath,$log){proc_terminate($process);proc_close($process);@unlink($configPath);@unlink($log);});

function ehttp(string $action,string $method='GET',?array $body=null,array &$session=[],array $headers=[]):array{
    $all=['Accept: application/json'];if($method!=='GET')$all[]='Content-Type: application/json';if(!empty($session['cookie']))$all[]='Cookie: '.$session['cookie'];if(!empty($session['csrfToken']))$all[]='X-CSRF-Token: '.$session['csrfToken'];array_push($all,...$headers);
    $context=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",$all),'content'=>$body===null?'':json_encode($body),'ignore_errors'=>true,'timeout'=>5]]);$response=@file_get_contents('http://127.0.0.1:8102/api/index.php?action='.$action,false,$context);$status=0;
    foreach($http_response_header??[] as $header){if(preg_match('/^HTTP\/\S+ (\d+)/',$header,$m))$status=(int)$m[1];if(preg_match('/^Set-Cookie: ([^;]+)/i',$header,$m))$session['cookie']=$m[1];}$json=json_decode($response?:'{}',true)?:[];if(isset($json['csrfToken']))$session['csrfToken']=$json['csrfToken'];return ['status'=>$status,'json'=>$json];
}
function agent_call(string $token,string $requestId,string $operation,array $payload):array{$session=[];return ehttp('prospecting-agent-ingest','POST',['request_id'=>$requestId,'operation'=>$operation,'payload'=>$payload],$session,['Authorization: Bearer '.$token]);}
for($i=0;$i<30;$i++){if(ehttp('status')['status']===200)break;usleep(100000);}
echeck(ehttp('prospecting-agent-ingest','POST',['request_id'=>'unauth-0001','operation'=>'CREATE_RUN','payload'=>[]])['status']===403,'internal ingest rejects missing service authentication');
echeck(agent_call(str_repeat('e',64),'wrong-token-0001','CREATE_RUN',[])['status']===403,'internal ingest rejects wrong service token');
$one=[];$two=[];$password='fictional-test-password-only';ehttp('login','POST',['email'=>'one@example.test','password'=>$password],$one);ehttp('login','POST',['email'=>'two@example.test','password'=>$password],$two);
echeck(ehttp('prospecting-agent-ingest','POST',['request_id'=>'session-only-001','operation'=>'CREATE_RUN','payload'=>[]],$one)['status']===403,'Studio browser session cannot authenticate internal ingest');

function create_mission(array &$session,string $name,int $budget):string{$payload=['name'=>$name,'objective'=>'Phase 3.5 persistence verification.','location'=>'Test location','target_categories'=>['villa'],'target_qualified_leads'=>2,'minimum_score'=>75,'mission_budget_centavos'=>$budget];$id=ehttp('prospecting-missions','POST',$payload,$session)['json']['mission']['public_id'];ehttp('prospecting-missions&id='.rawurlencode($id),'PATCH',['status'=>'READY'],$session);ehttp('prospecting-missions&id='.rawurlencode($id),'PATCH',['status'=>'RUNNING'],$session);return $id;}
function create_prospect(array &$session,string $name):string{return ehttp('prospecting-prospects','POST',['business_name'=>$name,'category'=>'villa','location'=>'Test location'],$session)['json']['prospect']['public_id'];}
function add_member(array &$session,string $mission,string $prospect):void{ehttp('prospecting-mission-prospects&mission_id='.rawurlencode($mission),'POST',['prospect_public_id'=>$prospect,'discovery_source'=>'MANUAL','mission_status'=>'ACTIVE'],$session);}

$missionA=create_mission($one,'Execution mission A',1000);$prospect=create_prospect($one,'Execution persistence villa');add_member($one,$missionA,$prospect);
echeck(agent_call($tokenOne,'run-no-mission01','CREATE_RUN',['prospect_public_id'=>$prospect,'status'=>'RUNNING'])['status']===422,'agent run requires an owner-scoped mission');
$createRunPayload=['mission_public_id'=>$missionA,'prospect_public_id'=>$prospect,'status'=>'RUNNING'];$createdRun=agent_call($tokenOne,'run-create-0001','CREATE_RUN',$createRunPayload);$run=$createdRun['json']['result']['run'];$runId=$run['public_id'];
echeck($createdRun['status']===201&&$run['status']==='RUNNING','internal API creates agent run');
$runReplay=agent_call($tokenOne,'run-create-0001','CREATE_RUN',$createRunPayload);echeck($runReplay['status']===201&&$runReplay['json']['idempotent_request_replay']===true&&$runReplay['json']['result']['run']['public_id']===$runId,'identical internal request replay returns stored response');
echeck(agent_call($tokenOne,'run-create-0001','CREATE_RUN',array_replace($createRunPayload,['status'=>'PENDING']))['status']===409,'conflicting internal request replay rejected');
echeck(count(ehttp('prospecting-runs&id='.rawurlencode($runId),'GET',null,$one)['json']['data'])===1,'Studio owner can read agent run');
echeck(count(ehttp('prospecting-runs&id='.rawurlencode($runId),'GET',null,$two)['json']['data'])===0,'other owner cannot read agent run');
$updated=agent_call($tokenOne,'run-update-0001','UPDATE_RUN',['run_public_id'=>$runId,'status'=>'RUNNING','step_count'=>1,'llm_call_count'=>0,'research_duration_ms'=>1000]);echeck($updated['status']===200&&$updated['json']['result']['run']['step_count']===1,'internal API updates run counters');
echeck(agent_call($tokenOne,'run-stop-invalid-1','UPDATE_RUN',['run_public_id'=>$runId,'status'=>'STOPPED','stop_reason'=>'NOT_REAL'])['status']===422,'invalid agent stop reason rejected');
echeck(agent_call($tokenTwo,'run-cross-owner1','UPDATE_RUN',['run_public_id'=>$runId,'status'=>'RUNNING','step_count'=>2])['status']===404,'cross-owner agent run update denied');

$decision=['run_public_id'=>$runId,'step_number'=>1,'action'=>'INSPECT_WEBSITE','reason'=>'Need first-party evidence.','target'=>'https://example.com','expected_information'=>'Property presentation','authority_result'=>'ALLOWED','budget_result'=>'ALLOW_FREE','estimated_cost_centavos'=>0,'actual_cost_centavos'=>0,'confidence'=>0.9,'state_before'=>['status'=>'DISCOVERED'],'state_after'=>['status'=>'RESEARCHING'],'governance_trace'=>['final'=>['result'=>'ALLOW']]];
$decisionResult=agent_call($tokenOne,'decision-append-01','APPEND_DECISION',$decision);echeck($decisionResult['status']===201&&$decisionResult['json']['result']['decision']['step_number']===1,'sequential agent decision appended');
echeck(agent_call($tokenOne,'decision-append-02','APPEND_DECISION',$decision)['status']===409,'duplicate agent decision step rejected');
echeck(agent_call($tokenOne,'decision-invalid-01','APPEND_DECISION',array_replace($decision,['step_number'=>2,'action'=>'SEND_EMAIL']))['status']===422,'invalid agent action rejected');
echeck(agent_call($tokenTwo,'decision-cross-001','APPEND_DECISION',$decision)['status']===404,'cross-owner decision append denied');
echeck(count(ehttp('prospecting-decisions&run_id='.rawurlencode($runId),'GET',null,$one)['json']['data'])===1,'Studio owner can read decision history');

$walk=['prospect_public_id'=>$prospect,'type'=>'WALKTHROUGH_CONCEPT','content'=>['title'=>'Arrival story','scenes'=>3]];
$walkOne=agent_call($tokenOne,'artifact-walk-001','CREATE_ARTIFACT',$walk);$walkTwo=agent_call($tokenOne,'artifact-walk-002','CREATE_ARTIFACT',array_replace($walk,['content'=>['title'=>'Arrival story revised','scenes'=>4]]));
$draft=agent_call($tokenOne,'artifact-draft-01','CREATE_ARTIFACT',['prospect_public_id'=>$prospect,'type'=>'OUTREACH_DRAFT','content'=>'Internal unsent draft.']);
echeck($walkOne['status']===201&&$walkOne['json']['result']['artifact']['delivery_status']==='INTERNAL_UNSENT','walkthrough concept stored as internal artifact');
echeck($draft['status']===201&&$draft['json']['result']['artifact']['delivery_status']==='INTERNAL_UNSENT','outreach draft stored without sending');
echeck($walkOne['json']['result']['artifact']['version']===1&&$walkTwo['json']['result']['artifact']['version']===2,'artifact versions increment deterministically');
echeck(agent_call($tokenOne,'artifact-invalid-1','CREATE_ARTIFACT',array_replace($walk,['type'=>'SEND_EMAIL']))['status']===422,'invalid artifact type rejected');
$artifactList=ehttp('prospecting-artifacts&prospect_id='.rawurlencode($prospect),'GET',null,$one);echeck(count($artifactList['json']['data'])===3,'Studio owner can list prospect artifacts');
$artifactVersion=ehttp('prospecting-artifacts&prospect_id='.rawurlencode($prospect).'&type=WALKTHROUGH_CONCEPT&version=1','GET',null,$one);echeck(count($artifactVersion['json']['data'])===1,'Studio owner can retrieve an artifact version');
echeck(ehttp('prospecting-artifacts&prospect_id='.rawurlencode($prospect),'GET',null,$two)['status']===404,'artifact reads enforce owner isolation');
echeck(agent_call($tokenTwo,'artifact-cross-001','CREATE_ARTIFACT',$walk)['status']===404,'artifact writes enforce owner isolation');

function reserve_payload(string $mission,int $cost,string $key,?string $prospect=null,?string $run=null):array{$payload=['mission_public_id'=>$mission,'provider'=>'fixture-provider','operation'=>'fixture-operation','estimated_cost_centavos'=>$cost,'idempotency_key'=>$key,'ttl_seconds'=>900];if($prospect!==null)$payload['prospect_public_id']=$prospect;if($run!==null)$payload['run_public_id']=$run;return $payload;}
$reserve300=reserve_payload($missionA,300,'reserve-mission-a-300',$prospect,$runId);$r300=agent_call($tokenOne,'reserve-request-001','RESERVE_BUDGET',$reserve300);$reservation300=$r300['json']['result']['reservation']['public_id'];echeck($r300['status']===201&&$r300['json']['result']['allowed'],'reservation inside mission and monthly budget succeeds');
$idem=agent_call($tokenOne,'reserve-request-002','RESERVE_BUDGET',$reserve300);echeck($idem['status']===201&&$idem['json']['result']['idempotent_replay']&&$idem['json']['result']['reservation']['public_id']===$reservation300,'identical reservation idempotency replay returns same record');
echeck(agent_call($tokenOne,'reserve-request-003','RESERVE_BUDGET',array_replace($reserve300,['estimated_cost_centavos'=>301]))['status']===409,'conflicting reservation idempotency replay rejected');
$r700=agent_call($tokenOne,'reserve-request-004','RESERVE_BUDGET',reserve_payload($missionA,700,'reserve-mission-a-700'));$reservation700=$r700['json']['result']['reservation']['public_id'];echeck($r700['status']===201&&$r700['json']['result']['mission_available_centavos']===0,'reservation exactly at remaining mission budget succeeds');
echeck(agent_call($tokenOne,'reserve-request-005','RESERVE_BUDGET',reserve_payload($missionA,1,'reserve-mission-a-over'))['json']['result']['decision']==='DENY_BUDGET','reservation above mission budget denied');
$release=agent_call($tokenOne,'release-request-001','RELEASE_RESERVATION',['reservation_public_id'=>$reservation300,'reason'=>'Tool not executed.']);echeck($release['status']===200&&$release['json']['result']['release']['reservation']['status']==='RELEASED','active reservation released');
$releaseAgain=agent_call($tokenOne,'release-request-002','RELEASE_RESERVATION',['reservation_public_id'=>$reservation300,'reason'=>'Repeated release.']);echeck($releaseAgain['status']===200&&$releaseAgain['json']['result']['release']['idempotent_replay'],'repeated release is idempotent');
$releasedReserveReplay=agent_call($tokenOne,'reserve-request-006','RESERVE_BUDGET',$reserve300);echeck($releasedReserveReplay['status']===409&&!$releasedReserveReplay['json']['result']['allowed']&&$releasedReserveReplay['json']['result']['decision']==='EXISTING_RELEASED','released reservation replay cannot authorize new spend');
$commitExact=agent_call($tokenOne,'commit-request-001','COMMIT_RESERVATION',['reservation_public_id'=>$reservation700,'actual_cost_centavos'=>700]);echeck($commitExact['status']===200&&$commitExact['json']['result']['reservation']['status']==='COMMITTED','reservation commits exact actual amount');
echeck(agent_call($tokenOne,'release-request-003','RELEASE_RESERVATION',['reservation_public_id'=>$reservation700,'reason'=>'Invalid release.'])['status']===409,'committed reservation cannot be released');

$missionB=create_mission($one,'Execution mission B',5000);$monthlyExact=agent_call($tokenOne,'reserve-monthly-001','RESERVE_BUDGET',reserve_payload($missionB,1150,'reserve-monthly-exact'));$monthlyReservation=$monthlyExact['json']['result']['reservation']['public_id'];echeck($monthlyExact['status']===201&&$monthlyExact['json']['result']['monthly_available_centavos']===0,'reservation exactly at remaining monthly budget succeeds');
echeck(agent_call($tokenOne,'reserve-monthly-002','RESERVE_BUDGET',reserve_payload($missionB,1,'reserve-monthly-over'))['json']['result']['reason']==='Monthly owner budget would be exceeded.','reservation above monthly budget denied');
agent_call($tokenOne,'release-monthly-01','RELEASE_RESERVATION',['reservation_public_id'=>$monthlyReservation,'reason'=>'Monthly boundary test complete.']);

$missionC=create_mission($one,'Execution mission C',1000);$lower=agent_call($tokenOne,'reserve-lower-0001','RESERVE_BUDGET',reserve_payload($missionC,400,'reserve-lower-actual'));$lowerId=$lower['json']['result']['reservation']['public_id'];$lowerCommit=agent_call($tokenOne,'commit-lower-0001','COMMIT_RESERVATION',['reservation_public_id'=>$lowerId,'actual_cost_centavos'=>250]);echeck($lowerCommit['status']===200&&$lowerCommit['json']['result']['unused_reservation_released_centavos']===150,'commit lower than estimate records actual and releases unused amount');
$above=agent_call($tokenOne,'reserve-above-0001','RESERVE_BUDGET',reserve_payload($missionC,200,'reserve-above-fit'));$aboveId=$above['json']['result']['reservation']['public_id'];$aboveCommit=agent_call($tokenOne,'commit-above-0001','COMMIT_RESERVATION',['reservation_public_id'=>$aboveId,'actual_cost_centavos'=>300]);echeck($aboveCommit['status']===200&&$aboveCommit['json']['result']['reservation']['actual_cost_centavos']===300,'above-estimate commit succeeds when both budgets still fit');
$noRoom=agent_call($tokenOne,'reserve-noroom-001','RESERVE_BUDGET',reserve_payload($missionC,450,'reserve-above-no-room'));$noRoomId=$noRoom['json']['result']['reservation']['public_id'];$reconcile=agent_call($tokenOne,'commit-noroom-001','COMMIT_RESERVATION',['reservation_public_id'=>$noRoomId,'actual_cost_centavos'=>451]);echeck($reconcile['status']===409&&$reconcile['json']['result']['decision']==='RECONCILIATION_REQUIRED'&&$reconcile['json']['result']['reservation']['status']==='RECONCILIATION_REQUIRED','above-estimate commit without budget enters reconciliation state');

$missionD=create_mission($one,'Execution mission D',500);$expired=agent_call($tokenOne,'reserve-expire-001','RESERVE_BUDGET',reserve_payload($missionD,100,'reserve-expiry-test'));$expiredId=$expired['json']['result']['reservation']['public_id'];$expire=$pdo->prepare("update prospecting_budget_reservations set expires_at=utc_timestamp()-interval 1 second where public_id=?");$expire->execute([$expiredId]);
$expiredRelease=agent_call($tokenOne,'release-expire-001','RELEASE_RESERVATION',['reservation_public_id'=>$expiredId,'reason'=>'Recover expired reservation.']);echeck($expiredRelease['status']===200&&$expiredRelease['json']['result']['release']['reservation']['status']==='EXPIRED','expired reservation is recovered without consuming budget');
$expiredAgain=agent_call($tokenOne,'release-expire-002','RELEASE_RESERVATION',['reservation_public_id'=>$expiredId,'reason'=>'Repeated expiry recovery.']);echeck($expiredAgain['status']===200&&$expiredAgain['json']['result']['release']['idempotent_replay'],'expired reservation recovery is idempotent');

$missionE=create_mission($one,'Execution mission E',500);
$worker='require "/app/public/api/prospecting.php";require "/app/public/api/prospecting-agent-ingest.php";$p=new PDO("mysql:host=db;dbname=review_test;charset=utf8mb4","root","fictional-local-test-only",[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$p->exec("set time_zone=\"+00:00\"");$p->beginTransaction();$o=$p->prepare("select id from studio_users where id=1 for update");$o->execute();$r=prospecting_agent_reserve($p,1,["prospecting_agent_monthly_budget_centavos"=>2000],["mission_public_id"=>$argv[1],"provider"=>"fixture","operation"=>"concurrent","estimated_cost_centavos"=>400,"idempotency_key"=>$argv[2],"ttl_seconds"=>900]);usleep(150000);$p->commit();echo $r["decision"];';
$workers=[];foreach(['concurrent-reserve-a','concurrent-reserve-b'] as $key){$pipes=[];$proc=proc_open(['php','-r',$worker,$missionE,$key],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);fclose($pipes[0]);$workers[]=[$proc,$pipes];}$outcomes=[];foreach($workers as [$proc,$pipes]){$outcomes[]=stream_get_contents($pipes[1]);fclose($pipes[1]);$errors=stream_get_contents($pipes[2]);fclose($pipes[2]);echeck(proc_close($proc)===0&&$errors==='','concurrent reservation worker completed');}sort($outcomes);echeck($outcomes===['ALLOW','DENY_BUDGET'],'concurrent reservations cannot double-spend mission budget');

$reservations=ehttp('prospecting-reservations&mission_id='.rawurlencode($missionA),'GET',null,$one);echeck(count($reservations['json']['data'])===2,'Studio owner can read reservation history');
echeck(count(ehttp('prospecting-reservations&mission_id='.rawurlencode($missionA),'GET',null,$two)['json']['data']??[])===0&&ehttp('prospecting-reservations&mission_id='.rawurlencode($missionA),'GET',null,$two)['status']===404,'reservation reads enforce owner isolation');

$completed=agent_call($tokenOne,'run-complete-001','UPDATE_RUN',['run_public_id'=>$runId,'status'=>'COMPLETED','step_count'=>1,'llm_call_count'=>0,'research_duration_ms'=>1500,'stop_reason'=>'QUALIFIED']);echeck($completed['status']===200&&$completed['json']['result']['run']['status']==='COMPLETED'&&$completed['json']['result']['run']['stop_reason']==='QUALIFIED','agent run completed with validated stop reason');
echo "{$checks} execution persistence integration checks passed. No agent tools, outreach, or promotion executed.\n";
