-- Additive CinematicFlight Prospecting v1 migration.
-- Apply after database/mysql-schema.sql. Existing Studio tables are unchanged.

create table if not exists prospecting_missions (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  name varchar(190) not null,
  objective text not null,
  location varchar(255) not null,
  target_categories_json text not null,
  target_qualified_leads int unsigned not null,
  minimum_score tinyint unsigned not null,
  mission_budget_centavos bigint unsigned not null,
  status varchar(40) not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  primary key (id),
  unique key prospecting_missions_public_unique (public_id),
  key prospecting_missions_owner_status_index (owner_id, status),
  constraint prospecting_missions_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_prospects (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  business_name varchar(190) not null,
  category varchar(120) not null,
  address varchar(500) null,
  location varchar(255) not null,
  website varchar(2048) null,
  phone varchar(80) null,
  rating decimal(3,2) null,
  review_count int unsigned null,
  external_source varchar(100) null,
  external_source_id varchar(255) null,
  normalized_domain varchar(255) null,
  status varchar(40) not null,
  contact_status varchar(40) not null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  primary key (id),
  unique key prospecting_prospects_public_unique (public_id),
  key prospecting_prospects_owner_status_index (owner_id, status),
  key prospecting_prospects_owner_domain_index (owner_id, normalized_domain),
  key prospecting_prospects_owner_source_index (owner_id, external_source, external_source_id),
  constraint prospecting_prospects_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_mission_prospects (
  id bigint unsigned not null auto_increment,
  mission_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  discovery_source varchar(120) not null,
  mission_status varchar(40) not null,
  rank int unsigned null,
  discovered_at timestamp not null default current_timestamp,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  primary key (id),
  unique key prospecting_mission_prospect_unique (mission_id, prospect_id),
  key prospecting_membership_prospect_index (prospect_id),
  constraint prospecting_membership_mission_fk foreign key (mission_id) references prospecting_missions(id) on delete cascade,
  constraint prospecting_membership_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_qualifications (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  version int unsigned not null,
  experience_gap_score tinyint unsigned not null,
  walkthrough_fit_score tinyint unsigned not null,
  commercial_fit_score tinyint unsigned not null,
  visual_property_score tinyint unsigned not null,
  contactability_score tinyint unsigned not null,
  penalty_score smallint not null,
  final_score tinyint unsigned not null,
  priority varchar(20) not null,
  qualification_status varchar(40) not null,
  confidence decimal(5,4) not null,
  experience_gap_summary text not null,
  primary_marketing_problem text not null,
  cinematicflight_opportunity text not null,
  scoring_rule_version varchar(80) not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_qualifications_public_unique (public_id),
  unique key prospecting_qualifications_version_unique (prospect_id, version),
  key prospecting_qualifications_owner_prospect_index (owner_id, prospect_id, id),
  constraint prospecting_qualifications_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_qualifications_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_contacts (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  type varchar(40) not null,
  value varchar(2048) not null,
  source_url varchar(2048) not null,
  verification_status varchar(40) not null,
  is_primary tinyint(1) not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  primary key (id),
  unique key prospecting_contacts_public_unique (public_id),
  key prospecting_contacts_owner_prospect_index (owner_id, prospect_id, id),
  constraint prospecting_contacts_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_contacts_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_agent_runs (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  mission_id bigint unsigned null,
  prospect_id bigint unsigned not null,
  status varchar(40) not null,
  started_at timestamp null,
  completed_at timestamp null,
  stop_reason varchar(60) null,
  step_count int unsigned not null default 0,
  llm_call_count int unsigned not null default 0,
  research_duration_ms bigint unsigned not null default 0,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp on update current_timestamp,
  primary key (id),
  unique key prospecting_agent_runs_public_unique (public_id),
  key prospecting_agent_runs_owner_prospect_index (owner_id, prospect_id, id),
  key prospecting_agent_runs_owner_mission_index (owner_id, mission_id, id),
  constraint prospecting_agent_runs_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_agent_runs_mission_fk foreign key (mission_id) references prospecting_missions(id) on delete restrict,
  constraint prospecting_agent_runs_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete restrict
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_evidence (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  agent_run_id bigint unsigned null,
  source_type varchar(40) not null,
  source_url varchar(2048) not null,
  page_title varchar(500) null,
  observation_type varchar(120) not null,
  claim text not null,
  observation text not null,
  content_hash char(64) character set ascii collate ascii_bin not null,
  captured_at timestamp not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_evidence_public_unique (public_id),
  key prospecting_evidence_owner_prospect_index (owner_id, prospect_id, id),
  key prospecting_evidence_agent_run_index (agent_run_id),
  key prospecting_evidence_content_hash_index (content_hash),
  constraint prospecting_evidence_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_evidence_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade,
  constraint prospecting_evidence_agent_run_fk foreign key (agent_run_id) references prospecting_agent_runs(id) on delete set null
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_artifacts (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  qualification_id bigint unsigned null,
  type varchar(40) not null,
  version int unsigned not null,
  content longtext not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_artifacts_public_unique (public_id),
  unique key prospecting_artifacts_version_unique (prospect_id, type, version),
  key prospecting_artifacts_owner_prospect_index (owner_id, prospect_id, id),
  constraint prospecting_artifacts_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_artifacts_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade,
  constraint prospecting_artifacts_qualification_fk foreign key (qualification_id) references prospecting_qualifications(id) on delete restrict
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_agent_decisions (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  agent_run_id bigint unsigned not null,
  step_number int unsigned not null,
  action varchar(80) not null,
  reason text not null,
  target varchar(2048) null,
  expected_information text null,
  authority_result varchar(40) not null,
  budget_result varchar(40) not null,
  estimated_cost_centavos bigint unsigned not null,
  actual_cost_centavos bigint unsigned null,
  confidence decimal(5,4) not null,
  state_before_json longtext not null,
  state_after_json longtext not null,
  governance_trace_json longtext not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_agent_decisions_public_unique (public_id),
  unique key prospecting_agent_decisions_step_unique (agent_run_id, step_number),
  key prospecting_agent_decisions_owner_run_index (owner_id, agent_run_id, id),
  constraint prospecting_agent_decisions_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_agent_decisions_run_fk foreign key (agent_run_id) references prospecting_agent_runs(id) on delete cascade
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_cost_events (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  mission_id bigint unsigned null,
  prospect_id bigint unsigned null,
  agent_run_id bigint unsigned null,
  provider varchar(120) not null,
  operation varchar(120) not null,
  estimated_cost_centavos bigint unsigned not null,
  actual_cost_centavos bigint unsigned null,
  idempotency_key varchar(190) character set ascii collate ascii_bin not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_cost_events_public_unique (public_id),
  unique key prospecting_cost_events_owner_idempotency_unique (owner_id, idempotency_key),
  key prospecting_cost_events_owner_mission_index (owner_id, mission_id, id),
  key prospecting_cost_events_owner_prospect_index (owner_id, prospect_id, id),
  key prospecting_cost_events_agent_run_index (agent_run_id),
  constraint prospecting_cost_events_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_cost_events_mission_fk foreign key (mission_id) references prospecting_missions(id) on delete restrict,
  constraint prospecting_cost_events_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete restrict,
  constraint prospecting_cost_events_agent_run_fk foreign key (agent_run_id) references prospecting_agent_runs(id) on delete restrict
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_approvals (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  qualification_id bigint unsigned null,
  action varchar(40) not null,
  status varchar(40) not null,
  payload_hash char(64) character set ascii collate ascii_bin not null,
  approved_by_owner_id bigint unsigned null,
  created_at timestamp not null default current_timestamp,
  resolved_at timestamp null,
  primary key (id),
  unique key prospecting_approvals_public_unique (public_id),
  key prospecting_approvals_owner_prospect_index (owner_id, prospect_id, id),
  key prospecting_approvals_qualification_index (qualification_id),
  constraint prospecting_approvals_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_approvals_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete cascade,
  constraint prospecting_approvals_qualification_fk foreign key (qualification_id) references prospecting_qualifications(id) on delete restrict,
  constraint prospecting_approvals_actor_fk foreign key (approved_by_owner_id) references studio_users(id) on delete restrict
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists prospecting_promotions (
  id bigint unsigned not null auto_increment,
  public_id varchar(80) character set ascii collate ascii_bin not null,
  owner_id bigint unsigned not null,
  prospect_id bigint unsigned not null,
  studio_inquiry_id bigint unsigned null,
  approval_id bigint unsigned not null,
  created_at timestamp not null default current_timestamp,
  primary key (id),
  unique key prospecting_promotions_public_unique (public_id),
  unique key prospecting_promotions_prospect_unique (prospect_id),
  key prospecting_promotions_owner_index (owner_id, id),
  constraint prospecting_promotions_owner_fk foreign key (owner_id) references studio_users(id) on delete cascade,
  constraint prospecting_promotions_prospect_fk foreign key (prospect_id) references prospecting_prospects(id) on delete restrict,
  constraint prospecting_promotions_inquiry_fk foreign key (studio_inquiry_id) references studio_inquiries(id) on delete restrict,
  constraint prospecting_promotions_approval_fk foreign key (approval_id) references prospecting_approvals(id) on delete restrict
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
