import { useEffect, useMemo, useState } from 'react';
import {
  ArrowLeft, ArrowRight, ArrowSquareOut, FileMagnifyingGlass, Plus, SealCheck, ShieldCheck, X,
} from '@phosphor-icons/react';
import { formatPhpCentavos, MISSION_TRANSITIONS, parsePhpToCentavos, prospectingApi } from '../lib/prospectingApi.js';
import './prospecting.css';

export const PROSPECTING_TABS = [
  ['overview', 'Overview'], ['missions', 'Missions'], ['prospects', 'Prospects'],
  ['approvals', 'Approvals'], ['activity', 'Agent Activity'], ['costs', 'Costs'],
];

const labels = {
  DISCOVERED: 'Discovered', RESEARCHING: 'Researching', INSUFFICIENT_EVIDENCE: 'Insufficient evidence',
  DISQUALIFIED: 'Disqualified', QUALIFIED: 'Qualified', PENDING_APPROVAL: 'Pending approval',
  APPROVED: 'Approved', REJECTED: 'Rejected', PROMOTED_TO_STUDIO: 'Promoted to Studio',
  BUDGET_EXHAUSTED: 'Budget exhausted', CONTACT_FORM_ONLY: 'Contact form only', SOCIAL_ONLY: 'Social only',
  NOT_FOUND: 'Not found', UNVERIFIED: 'Unverified', WALKTHROUGH_CONCEPT: 'Walkthrough concept',
  OUTREACH_DRAFT: 'Outreach draft', ALLOW_FREE: 'Allow — no cost', ALLOWED: 'Allowed', DENIED: 'Denied',
};

export const humanize = (value) => labels[value] || String(value || 'Unknown').toLowerCase().replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase());
export const formatDate = (value) => value ? new Intl.DateTimeFormat('en-PH', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value.replace(' ', 'T') + (value.includes('T') ? '' : 'Z'))) : '—';

export function prospectingRoute(pathname) {
  const parts = pathname.replace(/\/+$/, '').split('/').filter(Boolean);
  if (parts[0] !== 'prospecting') return { view: 'overview', id: null };
  if (parts[1] === 'missions' && parts[2]) return { view: 'mission', id: decodeURIComponent(parts[2]) };
  if (parts[1] === 'prospects' && parts[2]) return { view: 'prospect', id: decodeURIComponent(parts[2]) };
  return { view: PROSPECTING_TABS.some(([id]) => id === parts[1]) ? parts[1] : 'overview', id: null };
}

function StatusPill({ value, kind = 'status' }) {
  return <span className={`prospecting-pill is-${String(value).toLowerCase().replaceAll('_', '-')} ${kind === 'priority' ? 'is-priority' : ''}`}><i aria-hidden="true" />{humanize(value)}</span>;
}

function EmptyState({ title, children, action }) {
  return <section className="prospecting-empty"><FileMagnifyingGlass size={30} weight="light" aria-hidden="true" /><h3>{title}</h3><p>{children}</p>{action}</section>;
}

function Unavailable({ error, onRetry }) {
  return <section className="prospecting-unavailable" role="alert"><ShieldCheck size={34} aria-hidden="true" /><p className="prospecting-kicker">Private workspace locked</p><h2>Prospecting data is unavailable.</h2><p>{error || 'Studio could not verify the private Prospecting API. No cached or demonstration data has been shown.'}</p><button className="prospecting-button is-dark" type="button" onClick={onRetry}>Retry secure connection</button></section>;
}

function WorkspaceHeader({ route, navigate }) {
  return <><header className="prospecting-header"><div><p className="prospecting-kicker">Private prospecting desk</p><h1>{route.view === 'mission' ? 'Mission detail' : route.view === 'prospect' ? 'Prospect detail' : humanize(route.view)}</h1><p>Evidence-led qualification, owner decisions and research costs. Autonomous research and outreach are not enabled.</p></div><div className="prospecting-safety"><ShieldCheck size={18} weight="fill" aria-hidden="true" /><span>Owner verified</span><small>No outreach enabled</small></div></header><nav className="prospecting-tabs" aria-label="Prospecting sections">{PROSPECTING_TABS.map(([id, label]) => <button type="button" key={id} className={(route.view === id || (route.view === 'mission' && id === 'missions') || (route.view === 'prospect' && id === 'prospects')) ? 'is-active' : ''} onClick={() => navigate(`/prospecting${id === 'overview' ? '' : `/${id}`}`)}>{label}</button>)}</nav></>;
}

function Metric({ label, value, note }) {
  return <article className="prospecting-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</article>;
}

function Overview({ missions, prospects, reservations, costs, navigate, openMissionForm, openProspectForm }) {
  const active = missions.filter((item) => ['READY', 'RUNNING', 'PAUSED'].includes(item.status)).length;
  const count = (status) => prospects.filter((item) => item.status === status).length;
  const activeReserved = reservations.filter((item) => item.status === 'RESERVED').reduce((sum, item) => sum + item.reserved_cost_centavos, 0);
  const totalCost = Object.values(costs).reduce((sum, item) => sum + item.actual_cost_centavos, 0);
  return <div className="prospecting-stack"><section className="prospecting-metrics" aria-label="Prospecting overview">
    <Metric label="Active missions" value={active} /><Metric label="Discovered prospects" value={prospects.length} />
    <Metric label="Researching" value={count('RESEARCHING')} /><Metric label="Qualified" value={count('QUALIFIED')} />
    <Metric label="Pending approval" value={count('PENDING_APPROVAL')} /><Metric label="Approved" value={count('APPROVED')} />
    <Metric label="Rejected" value={count('REJECTED')} /><Metric label="Total research cost" value={formatPhpCentavos(totalCost)} /><Metric label="Active reserved budget" value={formatPhpCentavos(activeReserved)} />
  </section><p className="prospecting-footnote">A consolidated summary endpoint is recommended before showing cross-prospect HOT counts at production scale.</p><section className="prospecting-intro"><div><p className="prospecting-kicker">Owner workflow</p><h2>Define the search before research begins.</h2><p>Missions set the location, category, qualification threshold and hard PHP budget. Properties can be added manually now; automated discovery arrives in a later phase.</p><div className="prospecting-actions"><button className="prospecting-button is-dark" type="button" onClick={openMissionForm}><Plus size={17} />Create mission</button><button className="prospecting-button" type="button" onClick={openProspectForm}><Plus size={17} />Add prospect</button></div></div><ol><li><span>01</span><div><strong>Mission</strong><p>Scope and budget the objective.</p></div></li><li><span>02</span><div><strong>Evidence</strong><p>Observe sources without treating them as instructions.</p></div></li><li><span>03</span><div><strong>Owner decision</strong><p>Approve or reject only after qualification.</p></div></li></ol></section>
  <section className="prospecting-recent"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Current work</p><h2>Recent prospects</h2></div><button type="button" onClick={() => navigate('/prospecting/prospects')}>View all <ArrowRight size={16} /></button></div>{prospects.length ? <div className="prospecting-row-list">{prospects.slice(0, 5).map((prospect) => <button type="button" key={prospect.public_id} onClick={() => navigate(`/prospecting/prospects/${prospect.public_id}`)}><span><strong>{prospect.business_name}</strong><small>{prospect.category} · {prospect.location}</small></span><StatusPill value={prospect.status} /><ArrowRight size={16} aria-hidden="true" /></button>)}</div> : <EmptyState title="No prospects yet">Add a property manually. Automated discovery will be introduced in a later phase.</EmptyState>}</section></div>;
}

function MissionForm({ initial, onCancel, onSave, busy, error }) {
  const [form, setForm] = useState(() => ({ name: initial?.name || '', objective: initial?.objective || '', location: initial?.location || '', categories: initial?.target_categories?.join(', ') || '', target: initial?.target_qualified_leads?.toString() || '5', score: initial?.minimum_score?.toString() || '75', budget: initial ? `${Math.floor(initial.mission_budget_centavos / 100)}.${String(initial.mission_budget_centavos % 100).padStart(2, '0')}` : '' }));
  const [validation, setValidation] = useState('');
  const submit = (event) => {
    event.preventDefault(); const categories = form.categories.split(',').map((item) => item.trim()).filter(Boolean); const budget = parsePhpToCentavos(form.budget); const target = Number(form.target); const score = Number(form.score);
    if (!form.name.trim() || !form.objective.trim() || !form.location.trim() || !categories.length) return setValidation('Complete the mission name, objective, location and at least one category.');
    if (!Number.isInteger(target) || target < 1) return setValidation('Target qualified leads must be a positive whole number.');
    if (!Number.isInteger(score) || score < 0 || score > 100) return setValidation('Minimum score must be a whole number from 0 to 100.');
    if (budget === null) return setValidation('Enter the PHP budget as a positive amount with no more than two decimal places.');
    setValidation(''); onSave({ name: form.name.trim(), objective: form.objective.trim(), location: form.location.trim(), target_categories: categories, target_qualified_leads: target, minimum_score: score, mission_budget_centavos: budget });
  };
  const field = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  return <form className="prospecting-form" onSubmit={submit}><div className="prospecting-section-title"><div><p className="prospecting-kicker">{initial ? 'Mission settings' : 'Owner-defined objective'}</p><h2>{initial ? 'Edit mission' : 'Create mission'}</h2></div>{onCancel && <button className="prospecting-icon-button" type="button" onClick={onCancel} aria-label="Close mission form"><X size={20} /></button>}</div><div className="prospecting-form-grid"><label>Mission name<input maxLength="190" required value={form.name} onChange={(e) => field('name', e.target.value)} /></label><label>Location<input maxLength="255" required value={form.location} onChange={(e) => field('location', e.target.value)} /></label><label className="is-wide">Objective<textarea maxLength="10000" required rows="4" value={form.objective} onChange={(e) => field('objective', e.target.value)} /></label><label className="is-wide">Target categories<span>Separate categories with commas.</span><input required value={form.categories} onChange={(e) => field('categories', e.target.value)} placeholder="Private villa, boutique resort" /></label><label>Target qualified leads<input inputMode="numeric" required value={form.target} onChange={(e) => field('target', e.target.value)} /></label><label>Minimum score<input inputMode="numeric" required value={form.score} onChange={(e) => field('score', e.target.value)} /></label><label>Mission budget PHP<span>Stored as integer centavos.</span><div className="prospecting-money-input"><b>₱</b><input inputMode="decimal" required value={form.budget} onChange={(e) => field('budget', e.target.value)} placeholder="100.00" /></div></label></div>{(validation || error) && <p className="prospecting-form-error" role="alert">{validation || error}</p>}<div className="prospecting-actions">{onCancel && <button className="prospecting-button" type="button" onClick={onCancel}>Cancel</button>}<button className="prospecting-button is-dark" type="submit" disabled={busy}>{busy ? 'Saving…' : initial ? 'Save mission' : 'Create mission'}</button></div></form>;
}

function Missions({ missions, costs, navigate, openForm }) {
  return <section><div className="prospecting-section-title"><div><p className="prospecting-kicker">Bounded objectives</p><h2>Missions</h2></div><button className="prospecting-button is-dark" type="button" onClick={openForm}><Plus size={17} />Create mission</button></div>{missions.length ? <div className="prospecting-card-grid">{missions.map((mission) => { const cost = costs[mission.public_id]; return <button className="mission-card" type="button" key={mission.public_id} onClick={() => navigate(`/prospecting/missions/${mission.public_id}`)}><div><StatusPill value={mission.status} /><ArrowRight size={18} /></div><p className="prospecting-kicker">{mission.location}</p><h3>{mission.name}</h3><p>{mission.objective}</p><dl><div><dt>Target</dt><dd>{mission.target_qualified_leads} qualified</dd></div><div><dt>Minimum</dt><dd>{mission.minimum_score}/100</dd></div><div><dt>Budget</dt><dd>{formatPhpCentavos(mission.mission_budget_centavos)}</dd></div><div><dt>Remaining</dt><dd>{cost ? formatPhpCentavos(cost.remaining_budget_centavos) : 'Loading…'}</dd></div></dl><small>Created {formatDate(mission.created_at)}</small></button>; })}</div> : <EmptyState title="No missions yet" action={<button className="prospecting-button is-dark" type="button" onClick={openForm}>Create first mission</button>}>Create your first prospecting mission to define what kinds of properties you want to evaluate.</EmptyState>}</section>;
}

function MissionDetail({ id, client, missions, costs, reservations, navigate, fail, refresh }) {
  const mission = missions.find((item) => item.public_id === id); const [members, setMembers] = useState([]); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { let active = true; client.listMissionProspects(id).then((rows) => active && setMembers(rows)).catch(fail); return () => { active = false; }; }, [id, client, fail]);
  if (!mission) return <EmptyState title="Mission not found">This mission is not available to the signed-in owner.</EmptyState>;
  const save = async (payload) => { setBusy(true); setError(''); try { await client.updateMission(id, payload); await refresh(false); setEditing(false); } catch (caught) { setError(caught.message); } finally { setBusy(false); } };
  const transition = async (status) => { setBusy(true); setError(''); try { await client.updateMission(id, { status }); await refresh(false); } catch (caught) { setError(caught.message); } finally { setBusy(false); } };
  const cost = costs[id]; const held = reservations.filter((item) => item.mission_public_id === id && item.status === 'RESERVED').reduce((sum, item) => sum + item.reserved_cost_centavos, 0);
  return <div className="prospecting-stack"><button className="prospecting-back" type="button" onClick={() => navigate('/prospecting/missions')}><ArrowLeft size={16} />All missions</button>{editing ? <MissionForm initial={mission} onCancel={() => setEditing(false)} onSave={save} busy={busy} error={error} /> : <section className="mission-detail-hero"><div><StatusPill value={mission.status} /><p className="prospecting-kicker">{mission.location} · {mission.public_id}</p><h2>{mission.name}</h2><p>{mission.objective}</p><div className="prospecting-tags">{mission.target_categories.map((item) => <span key={item}>{item}</span>)}</div></div><aside><dl><div><dt>Target qualified</dt><dd>{mission.target_qualified_leads}</dd></div><div><dt>Minimum score</dt><dd>{mission.minimum_score}</dd></div><div><dt>Budget</dt><dd>{formatPhpCentavos(mission.mission_budget_centavos)}</dd></div><div><dt>Actual cost</dt><dd>{formatPhpCentavos(cost?.actual_cost_centavos ?? 0)}</dd></div><div><dt>Reserved</dt><dd>{formatPhpCentavos(held)}</dd></div><div><dt>Available</dt><dd>{formatPhpCentavos(Math.max(0, (cost?.remaining_budget_centavos ?? mission.mission_budget_centavos) - held))}</dd></div></dl><button className="prospecting-button" type="button" onClick={() => setEditing(true)}>Edit mission</button></aside></section>}
  {!editing && <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Lifecycle</p><h2>Available transitions</h2></div></div><div className="prospecting-actions">{(MISSION_TRANSITIONS[mission.status] || []).map((status) => <button className="prospecting-button" type="button" disabled={busy} key={status} onClick={() => transition(status)}>{humanize(status)}</button>)}{!(MISSION_TRANSITIONS[mission.status] || []).length && <p>This mission is in a terminal state.</p>}</div>{error && <p className="prospecting-form-error" role="alert">{error}</p>}</section>}
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Associated prospects</p><h2>{members.length} properties</h2></div></div>{members.length ? <div className="prospecting-row-list">{members.map((member) => <button type="button" key={member.prospect_public_id} onClick={() => navigate(`/prospecting/prospects/${member.prospect_public_id}`)}><span><strong>{member.business_name}</strong><small>{member.category} · {member.location}</small></span><StatusPill value={member.mission_status} /><ArrowRight size={16} /></button>)}</div> : <EmptyState title="No prospects in this mission">Add a property manually and assign it to this mission.</EmptyState>}</section></div>;
}

function ProspectForm({ missions, onCancel, onSave, busy, error }) {
  const [form, setForm] = useState({ business_name: '', category: '', location: '', address: '', website: '', phone: '', mission: missions[0]?.public_id || '' }); const [validation, setValidation] = useState('');
  const submit = (event) => { event.preventDefault(); if (!form.business_name.trim() || !form.category.trim() || !form.location.trim() || !form.mission) return setValidation('Business name, category, location and mission are required.'); if (form.website && !/^https?:\/\/[^\s]+$/i.test(form.website)) return setValidation('Website must be a complete HTTP or HTTPS address.'); setValidation(''); const { mission, ...payload } = form; onSave(Object.fromEntries(Object.entries(payload).filter(([, value]) => value.trim() !== '')), mission); };
  return <form className="prospecting-form" onSubmit={submit}><div className="prospecting-section-title"><div><p className="prospecting-kicker">Manual entry only</p><h2>Add prospect</h2></div><button className="prospecting-icon-button" type="button" onClick={onCancel} aria-label="Close prospect form"><X size={20} /></button></div><p className="prospecting-form-note">This saves owner-entered information only. No website, directory, contact, or AI research will run.</p><div className="prospecting-form-grid"><label>Business name<input maxLength="190" required value={form.business_name} onChange={(e) => setForm({ ...form, business_name: e.target.value })} /></label><label>Category<input maxLength="120" required value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>Location<input maxLength="255" required value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /></label><label>Mission<select required value={form.mission} onChange={(e) => setForm({ ...form, mission: e.target.value })}><option value="">Select mission</option>{missions.map((mission) => <option key={mission.public_id} value={mission.public_id}>{mission.name}</option>)}</select></label><label className="is-wide">Address<input maxLength="500" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} /></label><label>Website<input maxLength="2048" inputMode="url" placeholder="https://" value={form.website} onChange={(e) => setForm({ ...form, website: e.target.value })} /></label><label>Phone<input maxLength="80" inputMode="tel" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></label></div>{(validation || error) && <p className="prospecting-form-error" role="alert">{validation || error}</p>}<div className="prospecting-actions"><button className="prospecting-button" type="button" onClick={onCancel}>Cancel</button><button className="prospecting-button is-dark" type="submit" disabled={busy}>{busy ? 'Saving…' : 'Add prospect'}</button></div></form>;
}

function Prospects({ prospects, summaries, associations, navigate, openForm }) {
  const [filters, setFilters] = useState({ status: '', priority: '', location: '', contact: '' }); const options = (key) => [...new Set(prospects.map((item) => key === 'priority' ? summaries[item.public_id]?.priority : item[key]).filter(Boolean))];
  const rows = prospects.filter((item) => (!filters.status || item.status === filters.status) && (!filters.priority || summaries[item.public_id]?.priority === filters.priority) && (!filters.location || item.location === filters.location) && (!filters.contact || item.contact_status === filters.contact));
  return <section><div className="prospecting-section-title"><div><p className="prospecting-kicker">Evidence-led pipeline</p><h2>Prospects</h2></div><button className="prospecting-button is-dark" type="button" onClick={openForm}><Plus size={17} />Add prospect</button></div>{prospects.length ? <><div className="prospecting-filters" aria-label="Prospect filters">{[['status','Status'],['priority','Priority'],['location','Location'],['contact','Contact status']].map(([key, label]) => <label key={key}><span>{label}</span><select value={filters[key]} onChange={(e) => setFilters({ ...filters, [key]: e.target.value })}><option value="">All</option>{options(key === 'contact' ? 'contact_status' : key).map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label>)}</div><div className="prospecting-table-wrap"><table className="prospecting-table"><thead><tr><th>Business</th><th>Status</th><th>Score</th><th>Priority</th><th>Contact</th><th>Mission</th><th>Updated</th></tr></thead><tbody>{rows.map((prospect) => { const qualification = summaries[prospect.public_id]; return <tr key={prospect.public_id} onClick={() => navigate(`/prospecting/prospects/${prospect.public_id}`)}><td><button type="button" onClick={() => navigate(`/prospecting/prospects/${prospect.public_id}`)}><strong>{prospect.business_name}</strong><small>{prospect.category} · {prospect.location}</small></button></td><td><StatusPill value={prospect.status} /></td><td>{qualification?.final_score ?? '—'}</td><td>{qualification ? <StatusPill value={qualification.priority} kind="priority" /> : '—'}</td><td>{humanize(prospect.contact_status)}</td><td>{associations[prospect.public_id]?.join(', ') || '—'}</td><td>{formatDate(prospect.updated_at)}</td></tr>; })}</tbody></table></div>{!rows.length && <EmptyState title="No matching prospects">Adjust the filters to see another part of the pipeline.</EmptyState>}</> : <EmptyState title="No prospects yet" action={<button className="prospecting-button is-dark" type="button" onClick={openForm}>Add a property manually</button>}>Add a property manually. Automated discovery will be introduced in a later phase.</EmptyState>}</section>;
}

function QualificationPanel({ qualification }) {
  if (!qualification) return <EmptyState title="No qualification yet">This prospect has not been scored.</EmptyState>;
  const components = [['Experience gap', 'experience_gap_score'], ['Walkthrough fit', 'walkthrough_fit_score'], ['Commercial fit', 'commercial_fit_score'], ['Visual property', 'visual_property_score'], ['Contactability', 'contactability_score']];
  return <section className="qualification-panel"><div className="qualification-final"><p className="prospecting-kicker">Deterministic final score</p><strong>{qualification.final_score}</strong><span>/ 100</span><StatusPill value={qualification.priority} kind="priority" /><small>Confidence {Math.round(qualification.confidence * 100)}% · Rule {qualification.scoring_rule_version}</small></div><div className="qualification-components">{components.map(([label, key]) => <div key={key}><span>{label}</span><div><i style={{ width: `${qualification[key]}%` }} /><b>{qualification[key]}</b></div></div>)}<div className="qualification-penalty"><span>Penalty</span><strong>{qualification.penalty_score}</strong><p>{qualification.penalty_score < 0 ? 'The stored qualification includes a deterministic penalty. Individual penalty reasons are not exposed by the current API snapshot.' : 'No score penalty was applied.'}</p></div></div></section>;
}

function EvidenceList({ evidence }) {
  return evidence.length ? <div className="evidence-list">{evidence.map((item) => <article key={item.public_id}><header><div><p className="prospecting-kicker">{humanize(item.observation_type)}</p><h3>{item.page_title || humanize(item.source_type)}</h3></div><time>{formatDate(item.captured_at)}</time></header><dl><div><dt>Source inspected</dt><dd><a href={item.source_url} target="_blank" rel="noreferrer">{item.source_url}<ArrowSquareOut size={14} /></a></dd></div><div><dt>Observed</dt><dd>{item.observation}</dd></div><div><dt>Supports</dt><dd>{item.claim}</dd></div></dl></article>)}</div> : <EmptyState title="No evidence yet">Research has not been run for this prospect.</EmptyState>;
}

function ContactList({ contacts }) {
  return contacts.length ? <div className="contact-list">{contacts.map((item) => <article key={item.public_id}><div><StatusPill value={item.type} /><strong>{item.value}</strong>{item.is_primary && <small>Primary observed contact</small>}</div><div><StatusPill value={item.verification_status} /><a href={item.source_url} target="_blank" rel="noreferrer">Source <ArrowSquareOut size={14} /></a></div></article>)}</div> : <EmptyState title="No contacts found">No observed contact has been stored. The interface never generates or guesses contact details.</EmptyState>;
}

function ArtifactPanel({ artifacts }) {
  const latest = (type) => artifacts.filter((item) => item.type === type).sort((a, b) => b.version - a.version)[0]; const walk = latest('WALKTHROUGH_CONCEPT'); const draft = latest('OUTREACH_DRAFT');
  const journey = walk && (Array.isArray(walk.content) ? walk.content : Array.isArray(walk.content?.steps) ? walk.content.steps : Array.isArray(walk.content?.scenes) ? walk.content.scenes : null);
  return <div className="artifact-grid"><article><p className="prospecting-kicker">Walkthrough concept</p><h3>{walk ? `Version ${walk.version}` : 'Not generated'}</h3>{walk ? journey ? <ol className="artifact-journey">{journey.map((step, index) => <li key={`${index}-${typeof step === 'string' ? step : step?.title || index}`}><span>{index + 1}</span>{typeof step === 'string' ? step : step?.title || step?.name || JSON.stringify(step)}</li>)}</ol> : typeof walk.content === 'string' ? <p className="artifact-copy">{walk.content}</p> : <dl className="artifact-fields">{Object.entries(walk.content || {}).map(([key, value]) => <div key={key}><dt>{humanize(key)}</dt><dd>{typeof value === 'string' || typeof value === 'number' ? value : JSON.stringify(value)}</dd></div>)}</dl> : <p>No walkthrough concept generated yet.</p>}</article><article className="outreach-artifact"><div className="artifact-draft-label">Draft — not sent</div><p className="prospecting-kicker">Outreach draft</p><h3>{draft ? `Version ${draft.version}` : 'Not generated'}</h3>{draft ? <p className="artifact-copy">{typeof draft.content === 'string' ? draft.content : JSON.stringify(draft.content, null, 2)}</p> : <p>No outreach draft generated yet.</p>}<small>External outreach is unavailable. This screen has no send action.</small></article></div>;
}

function RunHistory({ runs, decisions, loadDecisions }) {
  return runs.length ? <div className="run-list">{runs.map((run) => <details key={run.public_id} onToggle={(event) => event.currentTarget.open && loadDecisions(run.public_id)}><summary><span><StatusPill value={run.status} /><strong>{run.stop_reason ? humanize(run.stop_reason) : 'Run in progress'}</strong><small>{formatDate(run.created_at)}</small></span><span>{run.step_count} steps · {run.llm_call_count} LLM calls · {(run.research_duration_ms / 1000).toFixed(1)}s</span></summary><div className="decision-list">{decisions[run.public_id] === undefined ? <p role="status">Open to load decision history.</p> : !decisions[run.public_id].length ? <EmptyState title="No decisions recorded">This run has no persisted decision history.</EmptyState> : decisions[run.public_id].map((decision) => <article key={decision.public_id}><header><span>Step {decision.step_number}</span><strong>{humanize(decision.action)}</strong><time>{formatDate(decision.created_at)}</time></header><p>{decision.reason}</p>{decision.target && <p><b>Target:</b> {decision.target}</p>}<dl><div><dt>Authority</dt><dd>{humanize(decision.authority_result)}</dd></div><div><dt>Budget</dt><dd>{humanize(decision.budget_result)}</dd></div><div><dt>Estimated</dt><dd>{formatPhpCentavos(decision.estimated_cost_centavos)}</dd></div><div><dt>Actual</dt><dd>{decision.actual_cost_centavos === null ? '—' : formatPhpCentavos(decision.actual_cost_centavos)}</dd></div><div><dt>Confidence</dt><dd>{Math.round(decision.confidence * 100)}%</dd></div></dl><details className="governance-trace"><summary>Governance trace</summary><pre>{JSON.stringify(decision.governance_trace, null, 2)}</pre></details></article>)}</div></details>)}</div> : <EmptyState title="No agent activity yet">Autonomous research is not enabled yet.</EmptyState>;
}

function ApprovalDialog({ prospect, qualification, action, onCancel, onConfirm, busy, error }) {
  const approving = action === 'APPROVE_PROSPECT'; return <div className="prospecting-dialog-backdrop"><section className="prospecting-dialog" role="dialog" aria-modal="true" aria-labelledby="approval-dialog-title"><button className="prospecting-icon-button" type="button" onClick={onCancel} aria-label="Close confirmation"><X size={20} /></button><SealCheck size={34} weight="light" aria-hidden="true" /><p className="prospecting-kicker">Owner confirmation</p><h2 id="approval-dialog-title">{approving ? 'Approve' : 'Reject'} {prospect.business_name}?</h2><p>{approving ? 'This confirms that the prospect is suitable for CinematicFlight sales pipeline review.' : 'This records the prospect as rejected for this qualification snapshot.'}</p><div className="approval-snapshot"><span>Score <b>{qualification.final_score}</b></span><span>Priority <b>{qualification.priority}</b></span><span>Version <b>{qualification.version}</b></span></div>{error && <p className="prospecting-form-error" role="alert">{error}</p>}<div className="prospecting-actions"><button className="prospecting-button" type="button" onClick={onCancel} disabled={busy}>Cancel</button><button className={`prospecting-button ${approving ? 'is-dark' : 'is-danger'}`} type="button" onClick={onConfirm} disabled={busy}>{busy ? 'Waiting for Studio…' : approving ? 'Approve prospect' : 'Reject prospect'}</button></div></section></div>;
}

function ResearchRequestPanel({ prospect, requests, onRequest, onCancel, busy, error }) {
  const [confirming, setConfirming] = useState(false); const active = requests.find((item) => ['PENDING', 'CLAIMED'].includes(item.status));
  const eligible = prospect.status === 'RESEARCHING' && Boolean(prospect.website);
  return <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Owner-controlled handoff</p><h2>Website research request</h2></div>{active && <StatusPill value={active.status} />}</div>
    <p>{active ? active.status === 'PENDING' ? 'Queued for a manual signed runner. It is not running yet.' : 'Claimed by the manual runner. The browser cannot inspect websites.' : eligible ? 'Request bounded first-party HTTPS evidence capture. No outreach, LLM analysis, or browser crawling will occur.' : 'Requires a researching prospect with a recorded official website.'}</p>
    {active ? <div className="prospecting-actions">{active.status === 'PENDING' && <button className="prospecting-button" type="button" onClick={() => onCancel(active.public_id)} disabled={busy}>Cancel request</button>}</div> : eligible && <div className="prospecting-actions"><button className="prospecting-button is-dark" type="button" onClick={() => setConfirming(true)} disabled={busy}>Request website research</button></div>}
    {error && <p className="prospecting-form-error" role="alert">{error}</p>}
    {requests.length > 0 && <div className="prospecting-row-list">{requests.slice(0, 3).map((item) => <article key={item.public_id}><span><strong>{humanize(item.status)}</strong><small>{formatDate(item.requested_at)} · {item.requested_url}</small></span>{item.website_research_id && <small>Research saved</small>}</article>)}</div>}
    {confirming && <div className="prospecting-dialog-backdrop"><section className="prospecting-dialog" role="dialog" aria-modal="true" aria-label="Confirm website research request"><button className="prospecting-icon-button" type="button" onClick={() => setConfirming(false)} aria-label="Close confirmation"><X size={20} /></button><p className="prospecting-kicker">Owner confirmation</p><h2>Request bounded website research?</h2><p>Studio will only queue this recorded HTTPS website for the manual signed runner. This does not send outreach or start research in your browser.</p><div className="prospecting-actions"><button className="prospecting-button" type="button" onClick={() => setConfirming(false)} disabled={busy}>Cancel</button><button className="prospecting-button is-dark" type="button" onClick={() => { setConfirming(false); onRequest(); }} disabled={busy}>Queue request</button></div></section></div>}
  </section>;
}

function ProspectDetail({ id, client, prospects, missions, navigate, fail, refresh }) {
  const base = prospects.find((item) => item.public_id === id); const [detail, setDetail] = useState(null); const [decisions, setDecisions] = useState({}); const [approvalAction, setApprovalAction] = useState(null); const [approvalError, setApprovalError] = useState(''); const [requestError, setRequestError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { const [prospect, evidence, contacts, qualifications, artifacts, approvals, runs, reservations, requests] = await Promise.all([client.getProspect(id), client.listEvidence(id), client.listContacts(id), client.listQualifications(id), client.listArtifacts(id), client.listApprovals(id), client.listRuns({ prospect_id: id }), client.listReservations({ prospect_id: id }), client.listWebsiteResearchRequests({ prospect_id: id })]); setDetail({ prospect, evidence, contacts, qualifications, artifacts, approvals, runs, reservations, requests }); } catch (error) { fail(error); } };
  useEffect(() => { load(); }, [id]);
  if (!base || !detail) return <p className="prospecting-loading" role="status">Loading private prospect record…</p>;
  const { prospect, evidence, contacts, qualifications, artifacts, approvals, runs, reservations, requests } = detail; const qualification = qualifications[0]; const latestApproval = approvals.at(-1); const committed = reservations.filter((item) => item.status === 'COMMITTED').reduce((sum, item) => sum + (item.actual_cost_centavos || 0), 0); const held = reservations.filter((item) => item.status === 'RESERVED').reduce((sum, item) => sum + item.reserved_cost_centavos, 0);
  const loadDecisions = async (runId) => { if (decisions[runId] !== undefined) return; try { setDecisions((current) => ({ ...current, [runId]: [] })); const rows = await client.listDecisions(runId); setDecisions((current) => ({ ...current, [runId]: rows })); } catch (error) { fail(error); } };
  const decide = async () => { setBusy(true); setApprovalError(''); try { await client.createApproval(id, { qualification_public_id: qualification.public_id, action: approvalAction, status: 'APPROVED', payload: { qualification_public_id: qualification.public_id, final_score: qualification.final_score, qualification_version: qualification.version } }); setApprovalAction(null); await refresh(false); await load(); } catch (error) { setApprovalError(error.message); } finally { setBusy(false); } };
  const requestResearch = async () => { setBusy(true); setRequestError(''); try { const memberships = await Promise.all(missions.filter((mission) => mission.status === 'RUNNING').map(async (mission) => [mission.public_id, await client.listMissionProspects(mission.public_id)])); const missionId = memberships.find(([, members]) => members.some((member) => member.prospect_public_id === id))?.[0]; if (!missionId) throw new Error('This prospect must belong to a running mission before research can be requested.'); await client.createWebsiteResearchRequest({ mission_public_id: missionId, prospect_public_id: id, idempotency_key: `studio-research-${crypto.randomUUID()}` }); await load(); } catch (error) { setRequestError(error.message); } finally { setBusy(false); } };
  const cancelResearch = async (requestId) => { setBusy(true); setRequestError(''); try { await client.cancelWebsiteResearchRequest(requestId); await load(); } catch (error) { setRequestError(error.message); } finally { setBusy(false); } };
  return <div className="prospecting-stack"><button className="prospecting-back" type="button" onClick={() => navigate('/prospecting/prospects')}><ArrowLeft size={16} />All prospects</button><section className="prospect-summary"><div><StatusPill value={prospect.status} /><p className="prospecting-kicker">{prospect.category} · {prospect.location}</p><h2>{prospect.business_name}</h2><p>{prospect.address || 'No address recorded.'}</p>{prospect.website && <a href={prospect.website} target="_blank" rel="noreferrer">Visit recorded website <ArrowSquareOut size={15} /></a>}</div><dl><div><dt>Contact status</dt><dd>{humanize(prospect.contact_status)}</dd></div><div><dt>Phone</dt><dd>{prospect.phone || 'Not found'}</dd></div><div><dt>Last updated</dt><dd>{formatDate(prospect.updated_at)}</dd></div><div><dt>Studio promotion</dt><dd>{prospect.status === 'PROMOTED_TO_STUDIO' ? 'Recorded' : 'Not promoted'}</dd></div></dl></section>
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Qualification</p><h2>Score composition</h2></div>{qualification && <StatusPill value={qualification.qualification_status} />}</div><QualificationPanel qualification={qualification} /></section>
  {qualification && <section className="experience-gap"><div><p className="prospecting-kicker">Experience gap</p><strong>{qualification.experience_gap_score}<span>/100</span></strong><p>{qualification.experience_gap_summary}</p></div><dl><div><dt>Primary marketing problem</dt><dd>{qualification.primary_marketing_problem}</dd></div><div><dt>CinematicFlight opportunity</dt><dd>{qualification.cinematicflight_opportunity}</dd></div></dl></section>}
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Observed facts</p><h2>Evidence</h2></div><span>{evidence.length} records</span></div><EvidenceList evidence={evidence} /></section>
  <ResearchRequestPanel prospect={prospect} requests={requests} onRequest={requestResearch} onCancel={cancelResearch} busy={busy} error={requestError} />
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Publicly observed</p><h2>Contacts</h2></div></div><ContactList contacts={contacts} /></section>
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Internal generated work</p><h2>Artifacts</h2></div></div><ArtifactPanel artifacts={artifacts} /></section>
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Read-only history</p><h2>Agent activity</h2></div></div><RunHistory runs={runs} decisions={decisions} loadDecisions={loadDecisions} /></section>
  <section className="prospecting-panel"><div className="prospecting-section-title"><div><p className="prospecting-kicker">Research accounting</p><h2>Costs</h2></div></div><div className="prospecting-cost-pair"><Metric label="Committed" value={formatPhpCentavos(committed)} /><Metric label="Active reservation" value={formatPhpCentavos(held)} /></div>{reservations.length ? <ReservationTable reservations={reservations} /> : <p>No research costs or reservations recorded.</p>}</section>
  <section className="approval-panel"><div><p className="prospecting-kicker">Owner decision</p><h2>{prospect.status === 'PENDING_APPROVAL' ? 'Ready for your review' : humanize(prospect.status)}</h2><p>{latestApproval ? `${humanize(latestApproval.action)} was recorded ${formatDate(latestApproval.created_at)}. Approval does not mean promotion or outreach.` : 'No approval decision has been recorded.'}</p></div>{prospect.status === 'PENDING_APPROVAL' && qualification && <div className="prospecting-actions"><button className="prospecting-button is-dark" type="button" onClick={() => setApprovalAction('APPROVE_PROSPECT')}>Approve prospect</button><button className="prospecting-button is-danger" type="button" onClick={() => setApprovalAction('REJECT_PROSPECT')}>Reject prospect</button></div>}</section>{approvalAction && <ApprovalDialog prospect={prospect} qualification={qualification} action={approvalAction} onCancel={() => setApprovalAction(null)} onConfirm={decide} busy={busy} error={approvalError} />}</div>;
}

function ApprovalQueue({ prospects, summaries, navigate }) {
  const pending = prospects.filter((item) => item.status === 'PENDING_APPROVAL'); return <section><div className="prospecting-section-title"><div><p className="prospecting-kicker">Human gate</p><h2>Approvals</h2></div><span>{pending.length} waiting</span></div>{pending.length ? <div className="approval-queue">{pending.map((prospect) => { const qualification = summaries[prospect.public_id]; return <button type="button" key={prospect.public_id} onClick={() => navigate(`/prospecting/prospects/${prospect.public_id}`)}><span><strong>{prospect.business_name}</strong><small>{qualification?.experience_gap_summary || 'Open the prospect to review stored evidence.'}</small></span><span>{qualification ? <><b>{qualification.final_score}</b><StatusPill value={qualification.priority} kind="priority" /><small>Qualification v{qualification.version}</small></> : <small>Qualification unavailable</small>}</span><ArrowRight size={18} /></button>; })}</div> : <EmptyState title="No approvals waiting">Qualified prospects appear here only after they enter pending approval. Approved and promoted are separate states.</EmptyState>}</section>;
}

function ReservationTable({ reservations }) { return <div className="prospecting-table-wrap"><table className="prospecting-table"><thead><tr><th>Provider / operation</th><th>Estimated</th><th>Actual</th><th>Status</th><th>Created</th></tr></thead><tbody>{reservations.map((item) => <tr key={item.public_id}><td><strong>{item.provider}</strong><small>{humanize(item.operation)}</small></td><td>{formatPhpCentavos(item.estimated_cost_centavos)}</td><td>{item.actual_cost_centavos === null ? '—' : formatPhpCentavos(item.actual_cost_centavos)}</td><td><StatusPill value={item.status} /></td><td>{formatDate(item.created_at)}</td></tr>)}</tbody></table></div>; }

function AgentActivity({ runs, client, fail }) { const [decisions, setDecisions] = useState({}); const load = async (id) => { if (decisions[id] !== undefined) return; try { const rows = await client.listDecisions(id); setDecisions((current) => ({ ...current, [id]: rows })); } catch (error) { fail(error); } }; return <section><div className="prospecting-section-title"><div><p className="prospecting-kicker">Persisted history only</p><h2>Agent activity</h2></div><span>{runs.length} runs</span></div><RunHistory runs={runs} decisions={decisions} loadDecisions={load} /></section>; }

function CostDashboard({ missions, costs, reservations }) { const actual = Object.values(costs).reduce((sum, item) => sum + item.actual_cost_centavos, 0); const held = reservations.filter((item) => item.status === 'RESERVED').reduce((sum, item) => sum + item.reserved_cost_centavos, 0); return <section><div className="prospecting-section-title"><div><p className="prospecting-kicker">Integer PHP centavos</p><h2>Research costs</h2></div></div><div className="prospecting-cost-pair"><Metric label="Committed spend" value={formatPhpCentavos(actual)} /><Metric label="Active reservations" value={formatPhpCentavos(held)} /></div><div className="cost-missions">{missions.map((mission) => { const summary = costs[mission.public_id]; const missionHeld = reservations.filter((item) => item.mission_public_id === mission.public_id && item.status === 'RESERVED').reduce((sum, item) => sum + item.reserved_cost_centavos, 0); return <article key={mission.public_id}><header><div><StatusPill value={mission.status} /><h3>{mission.name}</h3></div><strong>{formatPhpCentavos(summary?.remaining_budget_centavos ?? mission.mission_budget_centavos)}<small>remaining before active holds</small></strong></header><dl><div><dt>Mission budget</dt><dd>{formatPhpCentavos(mission.mission_budget_centavos)}</dd></div><div><dt>Committed</dt><dd>{formatPhpCentavos(summary?.actual_cost_centavos ?? 0)}</dd></div><div><dt>Reserved</dt><dd>{formatPhpCentavos(missionHeld)}</dd></div><div><dt>Available</dt><dd>{formatPhpCentavos(Math.max(0, (summary?.remaining_budget_centavos ?? mission.mission_budget_centavos) - missionHeld))}</dd></div></dl></article>; })}</div>{reservations.length ? <><div className="prospecting-section-title is-sub"><div><p className="prospecting-kicker">Reservation ledger</p><h2>Operations</h2></div></div><ReservationTable reservations={reservations} /></> : <EmptyState title="No research costs yet">No provider charges or budget reservations have been persisted.</EmptyState>}<p className="prospecting-footnote">The current API exposes committed totals by mission and reservation-level operations. A consolidated cost-event list is a future summary endpoint.</p></section>; }

export default function ProspectingWorkspace({ routePath = window.location.pathname, onNavigate, onSessionExpired, client = prospectingApi }) {
  const route = prospectingRoute(routePath); const [core, setCore] = useState({ missions: [], prospects: [], runs: [], reservations: [] }); const [costs, setCosts] = useState({}); const [summaries, setSummaries] = useState({}); const [associations, setAssociations] = useState({}); const [loading, setLoading] = useState(true); const [fatal, setFatal] = useState(''); const [missionForm, setMissionForm] = useState(false); const [prospectForm, setProspectForm] = useState(false); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState('');
  useEffect(() => { window.scrollTo({ top: 0, left: 0, behavior: 'auto' }); }, [routePath]);
  const navigate = (path) => onNavigate?.(path); const fail = (error) => { setCore({ missions: [], prospects: [], runs: [], reservations: [] }); setCosts({}); setSummaries({}); setAssociations({}); setFatal(error?.message || 'The Prospecting API could not be verified.'); if (error?.status === 401) onSessionExpired?.(); };
  const refresh = async (showLoading = true) => { if (showLoading === true) setLoading(true); setFatal(''); try { const [missions, prospects, runs, reservations] = await Promise.all([client.listMissions(), client.listProspects(), client.listRuns(), client.listReservations()]); setCore({ missions, prospects, runs, reservations }); } catch (error) { fail(error); } finally { if (showLoading === true) setLoading(false); } };
  useEffect(() => { refresh(); }, [client]);
  const needsCosts = ['overview', 'missions', 'mission', 'costs'].includes(route.view); useEffect(() => { if (!needsCosts || !core.missions.length || fatal) return; Promise.all(core.missions.map(async (mission) => [mission.public_id, await client.getMissionCosts(mission.public_id)])).then((rows) => setCosts(Object.fromEntries(rows))).catch(fail); }, [needsCosts, core.missions, client, fatal]);
  const needsSummaries = ['prospects', 'approvals'].includes(route.view); useEffect(() => { if (!needsSummaries || !core.prospects.length || fatal) return; Promise.all(core.prospects.map(async (prospect) => [prospect.public_id, (await client.listQualifications(prospect.public_id))[0] || null])).then((rows) => setSummaries(Object.fromEntries(rows))).catch(fail); }, [needsSummaries, core.prospects, client, fatal]);
  useEffect(() => { if (route.view !== 'prospects' || !core.missions.length || fatal) return; Promise.all(core.missions.map(async (mission) => [mission, await client.listMissionProspects(mission.public_id)])).then((rows) => { const map = {}; rows.forEach(([mission, members]) => members.forEach((member) => { map[member.prospect_public_id] = [...(map[member.prospect_public_id] || []), mission.name]; })); setAssociations(map); }).catch(fail); }, [route.view, core.missions, client, fatal]);
  const createMission = async (payload) => { setSaving(true); setFormError(''); try { const mission = await client.createMission(payload); setMissionForm(false); await refresh(); navigate(`/prospecting/missions/${mission.public_id}`); } catch (error) { setFormError(error.message); } finally { setSaving(false); } };
  const createProspect = async (payload, missionId) => { setSaving(true); setFormError(''); try { const prospect = await client.createProspect(payload); await client.addMissionProspect(missionId, prospect.public_id); setProspectForm(false); await refresh(); navigate(`/prospecting/prospects/${prospect.public_id}`); } catch (error) { setFormError(error.message); } finally { setSaving(false); } };
  if (loading) return <section className="prospecting-workspace"><p className="prospecting-loading" role="status">Verifying private Prospecting data…</p></section>;
  if (fatal) return <section className="prospecting-workspace"><Unavailable error={fatal} onRetry={refresh} /></section>;
  let content = route.view === 'overview' ? <Overview {...core} costs={costs} navigate={navigate} openMissionForm={() => { setFormError(''); setMissionForm(true); }} openProspectForm={() => { setFormError(''); setProspectForm(true); }} /> : route.view === 'missions' ? <Missions missions={core.missions} costs={costs} navigate={navigate} openForm={() => { setFormError(''); setMissionForm(true); }} /> : route.view === 'mission' ? <MissionDetail id={route.id} client={client} missions={core.missions} costs={costs} reservations={core.reservations} navigate={navigate} fail={fail} refresh={refresh} /> : route.view === 'prospects' ? <Prospects prospects={core.prospects} summaries={summaries} associations={associations} navigate={navigate} openForm={() => { setFormError(''); setProspectForm(true); }} /> : route.view === 'prospect' ? <ProspectDetail id={route.id} client={client} prospects={core.prospects} missions={core.missions} navigate={navigate} fail={fail} refresh={refresh} /> : route.view === 'approvals' ? <ApprovalQueue prospects={core.prospects} summaries={summaries} navigate={navigate} /> : route.view === 'activity' ? <AgentActivity runs={core.runs} client={client} fail={fail} /> : <CostDashboard missions={core.missions} costs={costs} reservations={core.reservations} />;
  return <section className="prospecting-workspace"><WorkspaceHeader route={route} navigate={navigate} /><div className="prospecting-body">{content}</div>{missionForm && <div className="prospecting-dialog-backdrop"><section className="prospecting-dialog is-wide" role="dialog" aria-modal="true" aria-label="Create mission"><MissionForm onCancel={() => setMissionForm(false)} onSave={createMission} busy={saving} error={formError} /></section></div>}{prospectForm && <div className="prospecting-dialog-backdrop"><section className="prospecting-dialog is-wide" role="dialog" aria-modal="true" aria-label="Add prospect">{core.missions.length ? <ProspectForm missions={core.missions} onCancel={() => setProspectForm(false)} onSave={createProspect} busy={saving} error={formError} /> : <EmptyState title="Create a mission first" action={<button className="prospecting-button" type="button" onClick={() => { setProspectForm(false); setMissionForm(true); }}>Create mission</button>}>Every manually added prospect must belong to an owner-defined mission.</EmptyState>}</section></div>}</section>;
}

export { formatPhpCentavos, parsePhpToCentavos };
