export const MISSION_STATUSES = [
  "DRAFT", "READY", "RUNNING", "PAUSED", "COMPLETED", "CANCELLED", "FAILED", "BUDGET_EXHAUSTED",
] as const;

export const PROSPECT_STATUSES = [
  "DISCOVERED", "RESEARCHING", "INSUFFICIENT_EVIDENCE", "DISQUALIFIED", "QUALIFIED",
  "PENDING_APPROVAL", "APPROVED", "REJECTED", "PROMOTED_TO_STUDIO", "FAILED",
] as const;

export const CONTACT_TYPES = ["EMAIL", "PHONE", "CONTACT_FORM", "INSTAGRAM", "FACEBOOK", "OTHER"] as const;
export const CONTACT_VERIFICATION_STATUSES = ["VERIFIED", "UNVERIFIED"] as const;
export const CONTACT_STATUSES = ["FOUND", "CONTACT_FORM_ONLY", "SOCIAL_ONLY", "NOT_FOUND", "UNVERIFIED"] as const;
export const PRIORITIES = ["HOT", "HIGH", "MEDIUM", "LOW"] as const;

export const AGENT_ACTIONS = [
  "DISCOVER_MORE", "INSPECT_WEBSITE", "INSPECT_PAGE", "DETECT_EXISTING_EXPERIENCE", "FIND_CONTACT",
  "ANALYZE_EXPERIENCE_GAP", "CALCULATE_SCORE", "GENERATE_WALKTHROUGH", "DRAFT_OUTREACH",
  "SAVE_EVIDENCE", "SAVE_PROSPECT", "QUALIFY", "DISQUALIFY", "REQUEST_APPROVAL",
  "STOP_INSUFFICIENT_EVIDENCE", "STOP_BUDGET_LIMIT", "STOP_TOOL_LIMIT", "STOP_REPEATED_ACTION",
  "STOP_DUPLICATE", "STOP_POLICY_BLOCKED", "STOP_PAGE_LIMIT", "STOP_TIME_LIMIT",
  "STOP_TOOL_FAILURE", "STOP_RESEARCH_COMPLETE",
] as const;

export const STOP_REASONS = [
  "QUALIFIED", "DISQUALIFIED", "INSUFFICIENT_EVIDENCE", "BUDGET_LIMIT", "STEP_LIMIT", "PAGE_LIMIT",
  "LLM_LIMIT", "TIME_LIMIT", "TOOL_LIMIT", "REPEATED_ACTION", "DUPLICATE",
  "HUMAN_APPROVAL_REQUIRED", "TOOL_FAILURE", "FAILED", "RESEARCH_COMPLETE", "POLICY_BLOCKED",
] as const;

export type MissionStatus = typeof MISSION_STATUSES[number];
export type ProspectStatus = typeof PROSPECT_STATUSES[number];
export type ContactType = typeof CONTACT_TYPES[number];
export type ContactVerificationStatus = typeof CONTACT_VERIFICATION_STATUSES[number];
export type ContactStatus = typeof CONTACT_STATUSES[number];
export type Priority = typeof PRIORITIES[number];
export type AgentAction = typeof AGENT_ACTIONS[number];
export type StopReason = typeof STOP_REASONS[number];
